version: '3.7'

services:
  postgres:
    image: postgres:16
    container_name: 'test-case-postgres-${NODE_ENV}'
    restart: unless-stopped
    environment:
      - 'POSTGRES_HOST=test-case-postgres-${NODE_ENV}'
      - 'POSTGRES_PORT=${POSTGRES_PORT_INTERNAL}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_DB=${POSTGRES_DB}'
    ports:
      - '${POSTGRES_PORT_EXTERNAL}:${POSTGRES_PORT_INTERNAL}'
    volumes:
      - '../db/${NODE_ENV}/data:/var/lib/postgresql/data'

  redis:
    image: redis
    container_name: 'test-case-redis'
    restart: unless-stopped
    ports:
      - '${REDIS_PORT_EXTERNAL}:${REDIS_PORT_INTERNAL}'
    logging:
      driver: local
    volumes:
      - '../db/${NODE_ENV}/redis:/data'
